Repository unicsmcr/unics_social_api, pull requests merged in 2020-08, with the labels that each got.

#41 feat: add event channels and messages
  package-lock.json
  package.json
  src/controllers/MessageController.ts
  src/entities/Channel.ts
  src/entities/Event.ts
  src/entities/Message.ts
  src/index.ts
  src/routes/MessageRoutes.ts
  src/services/EventService.ts
  src/services/MessageService.ts
  tests/fixtures/events.ts
  tests/fixtures/messages.ts
  tests/integration/controllers/messageController.test.ts
  tests/unit/services/eventService.test.ts
  tests/unit/services/messageService.test.ts
Labels: enhancement

#45 feat: DM channels
  src/controllers/MessageController.ts
  src/controllers/UserController.ts
  src/entities/Channel.ts
  src/entities/User.ts
  src/index.ts
  src/routes/ChannelRoutes.ts
  src/routes/UserRoutes.ts
  src/routes/middleware/getChannel.ts
  src/services/ChannelService.ts
  src/services/UserService.ts
Labels: enhancement

#53 feat: implement discovery queue
  src/controllers/GatewayController.ts
  src/controllers/UserController.ts
  src/entities/Profile.ts
  src/entities/User.ts
  src/services/UserService.ts
  src/util/discovery/DiscoveryQueue.ts
  src/util/gateway/index.ts
  tests/integration/controllers/userController.test.ts
  tests/unit/services/userService.test.ts
Labels: enhancement, gateway

#56 feat(users)!: implement ability to upload profile pictures
  .gitignore
  assets/.gitkeep
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/entities/Profile.ts
  src/index.ts
  src/routes/UserRoutes.ts
  src/services/UserService.ts
  tests/fixtures/users.ts
  tests/integration/controllers/userController.test.ts
  tests/unit/services/userService.test.ts
Labels: enhancement

#55 feat(channels): order channels by last modified timestamp in /channels endpoint
  src/controllers/MessageController.ts
  src/entities/Channel.ts
  src/services/ChannelService.ts
  src/services/MessageService.ts
Labels: enhancement

#57 feat: implement gateway heartbeating
  package.json
  src/controllers/GatewayController.ts
  src/util/gateway/index.ts
  tests/integration/app.test.ts
  tests/integration/controllers/eventController.test.ts
  tests/integration/controllers/gatewayController.test.ts
  tests/integration/controllers/messageController.test.ts
  tests/integration/controllers/userController.test.ts
  tests/unit/services/eventService.test.ts
  tests/unit/services/messageService.test.ts
  tests/unit/services/userService.test.ts
  tests/util/dbTeardown.ts
  tests/util/setup.ts
Labels: enhancement, gateway

#60 fix: DM channels allow only registered users
  src/routes/middleware/getChannel.ts
  tests/fixtures/users.ts
  tests/unit/middleware/getChannel.test.ts
Labels: enhancement

#59 feat(video): twilio integration
  .env.example
  Makefile
  package-lock.json
  package.json
  src/controllers/GatewayController.ts
  src/controllers/UserController.ts
  src/entities/Channel.ts
  src/entities/VideoIntegration.ts
  src/entities/VideoUser.ts
  src/services/ChannelService.ts
  src/services/TwilioService.ts
  src/util/config/index.ts
  src/util/discovery/DiscoveryQueue.ts
  tests/integration/controllers/gatewayController.test.ts
  tests/unit/util/config/config.test.ts
  tests/util/setup.ts
Labels: enhancement

#62 feat: ability to customise host
  .env.example
  Makefile
  src/util/config/index.ts
  src/util/emails/index.ts
  tests/unit/util/config/config.test.ts
Labels: enhancement

#71 fix: editing startTime and endTime in events
  src/services/EventService.ts
Labels: fix
