Repository unicsmcr/unics_social_api, pull requests merged in 2020-09, with the labels that each got.

#73 feat: profile social media validation
  src/entities/Profile.ts
  src/services/UserService.ts
  tests/fixtures/users.ts
  tests/unit/services/userService.test.ts
Labels: enhancement

#74 feat: scoped JWTs
  package-lock.json
  src/controllers/UserController.ts
  src/entities/EmailConfirmation.ts
  src/routes/ChannelRoutes.ts
  src/routes/EventRoutes.ts
  src/routes/UserRoutes.ts
  src/routes/middleware/getUser.ts
  src/routes/middleware/isVerified.ts
  src/services/UserService.ts
  src/util/auth.ts
  src/util/emails/index.ts
  tests/fixtures/emailConfirmations.ts
  tests/integration/controllers/eventController.test.ts
  tests/integration/controllers/gatewayController.test.ts
  tests/integration/controllers/messageController.test.ts
  tests/integration/controllers/userController.test.ts
  tests/unit/middleware/getUser.test.ts
  tests/unit/services/userService.test.ts
  tests/unit/util/auth.test.ts
Labels: enhancement

#81 feat: report a user
  src/controllers/UserController.ts
  src/entities/Report.ts
  src/entities/User.ts
  src/routes/UserRoutes.ts
  src/services/UserService.ts
  src/util/emails/index.ts
  tests/fixtures/users.ts
  tests/integration/controllers/userController.test.ts
  tests/unit/services/userService.test.ts
Labels: enhancement

#85 fix: DM channel creation and getChannelsForUser
  src/entities/Channel.ts
  src/services/ChannelService.ts
Labels: fix

#86 feat: initial typing implementation
  src/controllers/GatewayController.ts
  src/util/gateway/index.ts
Labels: enhancement, gateway

#90 feat: added linkedin to profile
  src/entities/Profile.ts
  src/services/UserService.ts
  tests/fixtures/users.ts
  tests/unit/services/userService.test.ts
Labels: enhancement

#98 fix: store timestamps with a timezone to prevent offset issues
  src/entities/Channel.ts
  src/entities/Event.ts
  src/entities/Message.ts
  src/entities/Report.ts
  src/entities/VideoIntegration.ts
  src/services/TwilioService.ts
  src/util/config/video.ts
Labels: fix

#100 refactor: switch to time-based pagination for getMessages
  src/controllers/MessageController.ts
  src/services/MessageService.ts
  tests/unit/services/messageService.test.ts
Labels: enhancement

#91 feat: resending verification email
  src/controllers/UserController.ts
  src/routes/UserRoutes.ts
  src/services/UserService.ts
Labels: enhancement

#105 feat: discord integration
  .env.example
  Makefile
  package-lock.json
  package.json
  src/controllers/DiscordController.ts
  src/entities/DiscordLink.ts
  src/entities/User.ts
  src/routes/UserRoutes.ts
  src/services/DiscordService.ts
  src/util/config/index.ts
  tests/unit/util/config/config.test.ts
  tsconfig.json
Labels: enhancement

#114 feat: email service
  .env.example
  Makefile
  package-lock.json
  package.json
  src/index.ts
  src/services/email/EmailService.ts
  src/services/email/MockEmailService.ts
  src/util/config/index.ts
  tests/unit/services/emailService.test.ts
  tests/unit/util/config/config.test.ts
Labels: enhancement

#115 feat: discord improvements
  .env.example
  Makefile
  src/routes/middleware/getUser.ts
  src/services/DiscordService.ts
  src/util/config/index.ts
  tests/unit/util/config/config.test.ts
Labels: enhancement

#119 fix: notes not being saved properly
  src/services/NoteService.ts
Labels: fix

#120 fix: show file size limit in error messages
  src/routes/middleware/uploadImg.ts
Labels: fix

#121 feat: add "other" to Course and Year
  src/entities/Profile.ts
Labels: enhancement

#122 feat: reports email env variable, gateway connection logging
  .env.example
  Makefile
  src/controllers/GatewayController.ts
  src/controllers/UserController.ts
  src/util/config/index.ts
  src/util/logger.ts
  tests/unit/util/config/config.test.ts
Labels: enhancement

#123 feat: security patches and rate limiting
  package-lock.json
  package.json
  src/entities/Profile.ts
  src/routes/ChannelRoutes.ts
  src/routes/UserRoutes.ts
  src/services/UserService.ts
  src/util/emails/index.ts
  src/util/ratelimits.ts
  src/util/sanitise.ts
Labels: fix
